Models/BindedCalcUnit.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebL_1.Models
{
    [BindProperties(SupportsGet = true)]
    public class BindedCalcUnit : CalcUnit
    {
        public int type { get; set; }
        public int Action()
        {
            return Action(type);
        }
    }
}

Models/CalcUnit.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebL_1.Models
{
//    [BindProperties(SupportsGet = true)]
    public class CalcUnit
    {
        public int a { get; set; }
        public int b { get; set; }
        public CalcUnit(int _a,int _b)
        {

            a = _a;
            b = _b;
        }
        public CalcUnit() { }
        public int Sum() { return a + b; }
        public int Min() { return a - b; }
        public int Mult() { return a * b; }
        public int Div()
        {
            try { return a / b; }
            catch (DivideByZeroException)
            {
                Console.WriteLine("Division by Zero. Operands reversed.");
                //throw ("Division by zero",e);
                return 0;
            }
        }
        public int Action(int type)
        {
            switch (type)
            {
                case 0: return Sum();
                case 1: return Min();
                case 2: return Mult();
                case 3: return Div();
                default: return 0;
            }
        }
    }

}

Models/ErrorViewModel.cs
using System;

namespace WebL_1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcServiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebL_1.Models;

namespace WebL_1.Controllers
{
    public class CalcServiceController : Controller
    {
  
      
        public IActionResult Manual(int a, int b, int type)
        {
             if (Request.Method == "POST")
            {
                ViewData["Title"] = "Result";
                ViewBag.formShow = "none";
                CalcUnit c = new CalcUnit(a, b);
                ViewBag.result = "<h2>" + c.Action(type) + "</h2>";
                return View("Main");
            }
            ViewData["Title"] = "Manual";
            ViewBag.formShow = "block";
            return View("Main");
        }


        [HttpGet]
        public IActionResult ManualWithSeparateHandlers()
        {
            ViewData["Title"] = "Manual with separate handlers";
            ViewBag.formShow = "block";
            return View("Main");
        }


        [HttpPost]
        public IActionResult ManualWithSeparateHandlers(int a,int b, int type)
        {
            ViewData["Title"] = "Result";
            ViewBag.formShow = "none";
            CalcUnit c = new CalcUnit(a, b);
            ViewBag.result = "<h2>" + c.Action(type) + "</h2>";
            return View("Main");
        }
        [HttpGet]
        public IActionResult ModelBindingInParameters()
        {
            ViewData["Title"] = "Model binding in parameters";
            ViewBag.formShow = "block";
            return View("Main");
        }
        [HttpPost]
        public IActionResult ModelBindingInParameters([Bind("a", "b")] CalcUnit c, int type)
        {
            ViewData["Title"] = "Result";
            ViewBag.formShow = "none";
            ViewBag.result = "<h2>" + c.Action(type) + "</h2>";
            return View("Main");
        }

        [HttpGet]
        public IActionResult ModelBindingInSeparateModel()
        {
            ViewData["Title"] = "Model binding in separate model";
            ViewBag.formShow = "block";
            return View("Main");
        }
        [HttpPost]
        public IActionResult ModelBindingInSeparateModel(BindedCalcUnit bc)
        {
            ViewData["Title"] = "Result";
            ViewBag.formShow = "none";
            ViewBag.result = "<h2>" + bc.Action() + "</h2>";
            return View("Main");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WebL_1.Models;

namespace WebL_1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CalcService/Main.cshtml
<h2 style="padding-bottom:20px">@ViewData["Title"]</h2>

<form method="post" style="display:@ViewBag.formShow">
    <input name="a" />
    <select name="type">
        <option value="0">+</option>
        <option value="1">-</option>
        <option value="2">*</option>
        <option value="3">/</option>
    </select>
    <input  name="b" />
    <input type="submit" value="Calculate" />
</form>

@Html.Raw(ViewBag.result)

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div style=" text-align:left">
    <h5 class="display-4"style="padding-bottom:20px">Form parameters parsing demo</h5>
    <ul>
        <li><a asp-controller="CalcService" asp-action="Manual">Manual parsing in single action</a></li>
        <li><a asp-controller="CalcService" asp-action="ManualWithSeparateHandlers">Manual parsing in separate actions</a></li>
        <li><a asp-controller="CalcService" asp-action="ModelBindingInParameters">Model binding (parameters)</a></li>
        <li><a asp-controller="CalcService" asp-action="ModelBindingInSeparateModel">Model binding (separate model)</a></li>

    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Backend2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Backend2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Backend2
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>